[package]
name = "ws_rooms"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = {version = "1.42.0", features = ["full"]}
axum = { version = "0.8.2", features = ["macros", "ws"] }
serde = { version = "1.0.215", features = ["derive"] }
futures-util = "0.3.31"
serde_json = "1.0.105"