// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CursorUpdate } from "./CursorUpdate";
import type { Operation } from "./Operation";

export type ClientMessageType = { "type": "JoinRoom", "data": { room_id: string, } } | { "type": "LeaveRoom" } | { "type": "UpdatedPresence", "data": { presence: CursorUpdate, } } | { "type": "UpdatedStorage", "data": { operations: Array<Operation<string>>, } };
