// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Operation<T> = { "Insert": { index: number, value: T, } } | { "Delete": { index: number, } } | { "Update": { index: number, value: T, } } | { "Batch": Array<Operation<T>> } | { "Move": { from: number, to: number, } };
